spring:
  application:
    name: config
  profiles:
     active: native
  cloud:
    config:
      enabled: true
      server:
        native:
          search-locations: classpath:/config
    bus:
      refresh:
        enabled: true
#        git:
#          uri: https://github.com/liangfuz/ConfigRepo
#    bus:
#      refresh:
#        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#endpoints:
#  spring:
#    cloud:
#      bus:
#        refresh:
#          enabled: true
server:
  port: 8888

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
