spring:
  application:
    name: config
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/shared
        git:
          uri: https://github.com/liangfuz/ConfigRepo

#  profiles:
#     active: native

server:
  port: 8888

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
