spring:
  application:
    name: order-service
#  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8861

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  security:
    enabled: false