spring:
  application:
    name: product-service

server:
  port: 8871

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true






